version: '3.9'
services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: news_db
    depends_on:
      - redis
      - db
    restart: on-failure
    volumes:
      - .:/app  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: news_db
    ports:
      - "5430:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "80:80"

 
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A immigo_news worker --loglevel=info
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: news_db
    depends_on:
      - redis
      - db
      - web
    volumes:
      - .:/app

volumes:
  redisdata:    